dist: trusty
language: python
python:
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - pip install pytest-cov
  - pip install python-coveralls
# command to run tests
script: pytest --cov=rpcx
after_success: coveralls
